# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deploy to GitHub Pages

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches: ["master"]

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set VITE_BASE
        run: |
          echo "VITE_BASE=https://${GITHUB_REPOSITORY_OWNER,,}.github.io/${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Set BASE_PATH
        run: |
          echo "BASE_PATH=/${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: npm

      - name: Install dependencies
        run: |
          cd examples/sveltekit
          npm install

      - name: build
        env:
          BASE_PATH: ${{ env.BASE_PATH }}
          VITE_BASE: ${{ env.VITE_BASE }}
        run: |
          touch docs/.nojekyll
          cd examples/sveltekit
          npm run build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          # this should match the `pages` option in your adapter-static options
          path: "docs/"

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/configure-pages@v3

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
