# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deploy to GitHub Pages

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches: ["master"]

jobs:
  build_site:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./examples/sveltekit
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set VITE_BASE
        run: |
          echo "VITE_BASE=https://${GITHUB_REPOSITORY_OWNER,,}.github.io/${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Set BASE_PATH
        run: |
          echo "BASE_PATH=/${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: npm
          cache-dependency-path: ./examples/sveltekit/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: wasm32-unknown-unknown, wasm32-wasi
          toolchain: nightly-x86_64-unknown-linux-gnu
          components: rust-src, rustfmt

      - name: Install binstall
        uses: taiki-e/install-action@cargo-binstall

      - name: Install cargo-component v0.7.0
        run: echo yes | cargo binstall cargo-component@0.13.2

      - name: Cargo component build Workspace
        run: |
          cargo component build
          cargo component build --release
        working-directory: .

      - name: build
        env:
          BASE_PATH: ${{ env.BASE_PATH }}
          VITE_BASE: ${{ env.VITE_BASE }}
        run: npm run build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          # this should match the `pages` option in your adapter-static options
          path: "docs/"
        working-directory: .

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/configure-pages@v3

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
